name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update package list and upgrade existing packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install required packages
        run: |
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libgstreamer1.0-dev \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            liblzma-dev \
            libreadline-dev \
            libunwind-dev \
            uuid-dev \
            gettext \
            aidl

      - name: Install Cython
        run: |
          pip install cython==0.29.33

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Install Android build tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3"

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Get current date for cache key
        id: get-date
        run: |
          echo "::set-output name=date::$(date -u '+%Y%m%d')"
        shell: bash

      - name: Cache Buildozer build directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./.buildozer/bin
