name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Get current date for cache key
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(date -u '+%Y%m%d')"
        shell: bash

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Adjust path as needed

      # Cache Buildozer build directory
      - name: Cache Buildozer build directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
            ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev \
            libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev \
            libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi7 gettext
          sudo apt-get install -y autopoint

      # Build with Buildozer
      - name: Build with Buildozer
        run: buildozer -v android debug

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ github.workspace }}/bin
